---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/vfarcic/terraform-controller-demo
  ref:
    branch: main

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-eks
  namespace: flux-system
spec:
  prune: true
  interval: 2m
  path: "./weaveworks"
  sourceRef:
    kind: GitRepository
    name: infra
  timeout: 3m
  healthChecks:
  - apiVersion: infra.contrib.fluxcd.io/v1alpha1
    kind: Terraform
    name: eks
    namespace: flux-system
