---

apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: eks
  namespace: flux-system
spec:
  path: ./eks
  approvePlan: auto
  interval: 2m
  varsFrom:
    kind: Secret
    name: aws-creds
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
